baseURL = "https://www.vigvam-db.cz/"
languageCode = "cs-cz"
title = "VIGVAM"

contentDir = "content/"
defaultContentLanguage = "cs"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableRobotsTXT = true
EnableGitInfo = true

[blackfriday]
  fractions = false   # do not render fractions
