[build]
publish = "public"
command = "hugo --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.89.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Redirecting vigvam-db.netlify.com to primary domain and HTTP to HTTPS
[[redirects]]
  from = "https://vigvam-db.netlify.com/*"
  to = "https://www.vigvam-db.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://vigvam-db.netlify.com/*"
  to = "http://www.vigvam-db.cz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.vigvam-db.cz/*"
  to = "https://www.vigvam-db.cz/:splat"
  status = 301
  force = true
