backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "teen" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Teen" # Used in the UI, ie.: "New Post"
    files:
      - file: "content/teen/predstaveni-cinnosti.md"
        label: "Představení činnosti"
        name: "predstaveni"
        fields:
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Text", name: "body", widget: "markdown"}
      - file: "content/teen/kurzy-a-akce.md"
        label: "Kurzy a akce"
        name: "kurzy-a-akce"
        fields:
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Podnadpis", name: "subtitle", widget: "string"}
          - {label: "Text", name: "body", widget: "markdown"}
